import{a as v,i,S}from"./assets/vendor-D8_O3--j.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();let $=15;const y=async(r,o)=>{try{const e=await v.get(`https://pixabay.com/api/?key=50871412-165a861e59de274a11f9f1fdc&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${$}`),{hits:n,totalHits:t}=e.data;return n.length===0?(i.error({message:"Sorry, no images found. Try another search."}),{hits:[],totalHits:0}):{hits:n,totalHits:t}}catch(e){return console.error(e),i.error({message:"Something went wrong. Please try again later."}),{hits:[],totalHits:0}}},p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more-button");let c=null;const g=r=>{const o=r.map(e=>`
      <li class="image-container">
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="image-footer">
          <p><b>Likes</b>: ${e.likes}</p>
          <p><b>Views</b>: ${e.views}</p>
          <p><b>Comments</b>: ${e.comments}</p>
          <p><b>Downloads</b>: ${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new S(".gallery a",{captionsData:"alt",captionDelay:250})},q=()=>{p.innerHTML=""};function b(){m.style.display="block"}function L(){m.style.display="none"}function B(){h.style.display="block"}function f(){h.style.display="none"}const M=document.querySelector(".form"),P=document.querySelector(".search-input"),H=document.querySelector(".load-more-button");let a=1,u="",d=0;const w=15;f();M.addEventListener("submit",async r=>{r.preventDefault();const o=P.value.trim();if(o!==""){b(),o!==u&&(u=o,q(),a=1);try{const{hits:e,totalHits:n}=await y(o,a);d=n,e.length>0&&(g(e),a++,(a-1)*w>=d?(f(),i.info({message:"We're sorry, but you've reached the end of search results."})):B())}catch(e){console.error("Error loading images:",e)}finally{L()}}});H.addEventListener("click",async()=>{b();try{const{hits:r}=await y(u,a);r.length>0&&(g(r),a++,O(),(a-1)*w>=d&&(f(),i.info({message:"We're sorry, but you've reached the end of search results."})))}catch(r){console.error("Error loading images:",r)}finally{L()}});function O(){const r=document.querySelector(".gallery .image-container");if(r){const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
